export {
  PERSON_DISPLAY_NAME_MAX_LENGTH,
  PERSON_MUTATION_ERRORS,
  PERSON_STATUSES,
  activePeople,
  createPerson,
  findPerson,
  generatePersonId,
  isPersonStatus,
  personFromRow,
  personStatusLabel,
  renamePerson,
  retirePerson,
  type Person,
  type PersonMutationError,
  type PersonMutationResult,
  type PersonStatus,
} from "./identity.js";
