export {
  OPTIONAL_COMMERCIAL_SCOPE_IDS,
  SITE_INSTALLATION_FREEZE_REASON,
  SITE_INSTALLATION_INCOMPLETE_REASON_IDS,
  SITE_INSTALLATION_LABEL,
  SITE_INSTALLATION_SCOPE_ID,
  commercialRequestHasOptionalScope,
  isKnownOptionalScopeId,
  normalizeOptionalScopeIds,
  presentSiteInstallationScope,
  projectSiteInstallationScope,
  sameOptionalScopeIds,
  siteInstallationBlocksQuoteFreeze,
  siteInstallationFreezeRefusal,
  siteInstallationIncompleteReasonLabel,
  siteInstallationIncompleteReasons,
  type OptionalCommercialScopeId,
  type SiteInstallationIncompleteReason,
  type SiteInstallationIncompleteReasonId,
  type SiteInstallationOperatorView,
  type SiteInstallationScopeProjection,
} from "./scope.js";
