export {
  CUSTOMER_DISPLAY_NAME_MAX_LENGTH,
  CUSTOMER_MUTATION_ERRORS,
  CUSTOMER_STATUSES,
  activeCustomers,
  copyFrozenCustomerIdentity,
  createCustomer,
  customerFromRow,
  customerStatusLabel,
  findCustomer,
  freezeCustomerIdentity,
  generateCustomerId,
  isCustomerStatus,
  renameCustomer,
  retireCustomer,
  type Customer,
  type CustomerMutationError,
  type CustomerMutationResult,
  type CustomerStatus,
  type FrozenCustomerIdentity,
} from "./identity.js";
